const ACTION_TYPES = {
    SET_NEW_POKEMON: 'SET_NEW_POKEMON',
    SET_IS_LOADING: 'SET_IS_LOADING',

    UPDATE_RANGES: 'UPDATE_RANGES',
    UPDATE_SINGLE_RANGE: 'UPDATE_SINGLE_RANGE'
};

export default ACTION_TYPES;