const ACTION_TYPES = {
    SET_NEW_POKEMON: 'SET_NEW_POKEMON',
    SET_IS_LOADING: 'SET_IS_LOADING',

    SET_NEW_CUSTOM_RANGES: 'SET_NEW_CUSTOM_RANGES',
    SET_EDITING_CUSTOM_RANGES: 'SET_EDITING_CUSTOM_RANGES'
};

export default ACTION_TYPES;